window.gcexports.globalLexicon = {
  "hello" : { "tk": 1, "name": "HELLO", "cls": "function", "length": 1 , "arity": 1 },
  "goodbye" : { "tk": 1, "name": "GOODBYE", "cls": "function", "length": 1 , "arity": 1 },
  "val" : { "tk": 1, "name": "VAL", "cls": "function", "length": 2 , "arity": 2 },
  "key" : { "tk": 1, "name": "KEY", "cls": "function", "length": 2 , "arity": 2 },
  "len" : { "tk": 1, "name": "LEN", "cls": "function", "length": 1 , "arity": 1 },
  "concat" : { "tk": 1, "name": "CONCAT", "cls": "function", "length": 1 , "arity": 1 },
  "add" : { "tk": 1, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
  "mul" : { "tk": 1, "name": "MUL", "cls": "function", "length": 2 , "arity": 2 },
  "pow" : { "tk": 1, "name": "POW", "cls": "function", "length": 2 , "arity": 2 },
  "style" : { "tk": 1, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
  "map" : { "tk": 1, "name": "MAP", "cls": "function", "length": 2, "arity": 2 },
  "apply" : { "tk": 1, "name": "APPLY", "cls": "function", "length": 2, "arity": 2 },
  "in" : { "tk": 1, "name": "IN", "cls": "function", "length": 0, "arity": 0 },
  "arg" : { "tk": 1, "name": "ARG", "cls": "function", "length": 1, "arity": 1 },
  "data" : { "tk": 1, "name": "DATA", "cls": "function", "length": 1, "arity": 1 },
  "button" : { "tk": 1, "name": "BUTTON", "cls": "function", "length": 2, "arity": 2 },
  "input" : { "tk": 1, "name": "INPUT", "cls": "function", "length": 1, "arity": 1 },
  "img" : { "tk": 1, "name": "IMG", "cls": "function", "length": 1, "arity": 1 },
  "svg" : { "tk": 1, "name": "SVG", "cls": "function", "length": 2, "arity": 2 },
  "path" : { "tk": 1, "name": "PATH", "cls": "function", "length": 2, "arity": 2 },
  "code" : { "tk": 1, "name": "CODE", "cls": "function", "length": 2, "arity": 2 },
  "a" : { "tk": 1, "name": "A", "cls": "function", "length": 2, "arity": 2 },
  "ol" : { "tk": 1, "name": "OL", "cls": "function", "length": 2, "arity": 2 },
  "ul" : { "tk": 1, "name": "UL", "cls": "function", "length": 2, "arity": 2 },
  "li" : { "tk": 1, "name": "LI", "cls": "function", "length": 2, "arity": 2 },
  "title" : { "tk": 1, "name": "TITLE", "cls": "function", "length": 2, "arity": 2 },
  "span" : { "tk": 1, "name": "SPAN", "cls": "function", "length": 2, "arity": 2 },
  "p" : { "tk": 1, "name": "P", "cls": "function", "length": 2, "arity": 2 },
  "h3" : { "tk": 1, "name": "H3", "cls": "function", "length": 1, "arity": 1 },
  "div" : { "tk": 1, "name": "DIV", "cls": "function", "length": 2, "arity": 2 },
  "table" : { "tk": 1, "name": "TABLE", "cls": "function", "length": 2, "arity": 2 },
  "thead" : { "tk": 1, "name": "THEAD", "cls": "function", "length": 2, "arity": 2 },
  "td" : { "tk": 1, "name": "TD", "cls": "function", "length": 2, "arity": 2 },
  "th" : { "tk": 1, "name": "TH", "cls": "function", "length": 2, "arity": 2 },
  "tr" : { "tk": 1, "name": "TR", "cls": "function", "length": 2, "arity": 2 }

}
